apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerrit
  namespace: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerrit
  template:
    metadata:
      labels:
        app: gerrit
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: gerrit
        image: openfrontier/gerrit:2.16.8
        ports:
        - containerPort: 29418
        - containerPort: 8080
        env:
        - name: AUTH_TYPE
          value: DEVELOPMENT_BECOME_ANY_ACCOUNT
        - name: WEBURL
          value: "http://service.bitsly.org:8070"
---
apiVersion: v1
kind: Service
metadata:
  name: gerrit
  namespace: middleware
spec:
  selector:
    app: gerrit
  externalIPs:
  - 192.168.192.111
  - 192.168.11.111
  ports:
  - name: 29418port
    port: 29418
    targetPort: 29418
  - name: 8070port
    port: 8070
    targetPort: 8080
