apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-configmap
  namespace: middleware
data:
  squid.conf: |
    http_port 0.0.0.0:3128
    http_access allow all

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  namespace: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: squid
        image: sameersbn/squid:3.5.27
        ports:
        - containerPort: 3128
        volumeMounts:
        - name: squid-config-volume
          mountPath: /etc/squid/squid.conf
          subPath: squid.conf
      volumes:
      - name: squid-config-volume
        configMap:
          name: squid-configmap
          items:
          - key: squid.conf
            path: squid.conf

---
apiVersion: v1
kind: Service
metadata:
  name: squid
  namespace: middleware
spec:
  externalIPs:
  - 192.168.11.3
  ports:
  - name: 3128port
    port: 3128
    targetPort: 3128
  selector:
    app: squid

