apiVersion: v1
kind: ConfigMap
metadata:
  name: v2ray-configmap
  namespace: middleware
data:
  config.json: |
    {
      "inbounds": [
        {
          "port": 1087,
          "listen": "0.0.0.0",
          "protocol": "http",
          "sniffing": {
            "enabled": true,
            "destOverride": ["http", "tls"]
          },
          "settings": {
            "auth": "noauth",
            "udp": true
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "vmess",
          "settings": {
            "vnext": [
              {
                "address": "",
                "port": 443,
                "users": [
                  {
                    "id": "",
                    "alterId": 64,
                    "security": "auto",
                    "level": 0
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "ws",
            "security": "tls",
            "wsSettings": {
              "path": "/"
            }
          },
          "tlsSettings": {
              "allowInsecure": false
          },
          "mux": {
            "enabled": true,
            "concurrency": 8
          }
        }
      ]
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray
  namespace: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2ray
  template:
    metadata:
      labels:
        app: v2ray
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: v2ray
        image: v2ray/official
        ports:
        - containerPort: 1087
        volumeMounts:
        - name: v2ray-config-volume
          mountPath: /etc/v2ray/config.json
          subPath: config.json
      volumes:
      - name: v2ray-config-volume
        configMap:
          name: v2ray-configmap
          items:
          - key: config.json
            path: config.json

---
apiVersion: v1
kind: Service
metadata:
  name: v2ray
  namespace: middleware
spec:
  externalIPs:
  - 192.168.11.3
  ports:
  - name: 1087port
    port: 1087
    targetPort: 1087
  selector:
    app: v2ray

