apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: zookeeper
        image: zookeeper:3.3
        ports:
        - containerPort: 2181

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: middleware
spec:
  externalIPs:
  - 192.168.192.111
  - 192.168.11.111
  ports:
  - name: 2181port
    port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
